#!/usr/bin/env python3

import hashlib
import argparse

def crack_md5_hash(hash_to_crack, wordlist_path):
    with open(wordlist_path, 'r') as wordlist_file:
        wordlist = wordlist_file.read().splitlines()

    for password in wordlist:
        hashed_password = hashlib.md5(password.encode()).hexdigest()
        if hashed_password == hash_to_crack:
            return password
        else:
            print(f"Incorrect password: {password}")

    return False

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--hash", help="MD5 hash to crack", required=True)
    parser.add_argument("--wordlist", help="Path to the wordlist file", required=True)
    args = parser.parse_args()

    result = crack_md5_hash(args.hash, args.wordlist)

    if result:
        print(f"\nPassword found: {result}")
    else:
        print("\nPassword not found in the wordlist.")
