#!/usr/bin/env python3

import hashlib
import time

def crack_md5_hash(hash_to_crack, wordlist_path):
    with open(wordlist_path, 'r') as wordlist_file:
        wordlist = wordlist_file.read().splitlines()

    for password in wordlist:
        hashed_password = hashlib.md5(password.encode()).hexdigest()
        if hashed_password == hash_to_crack:
            return password
        else:
            print(f"Incorrect password: {password}")
            time.sleep(1)  # Animasi jeda satu detik

    return False

if __name__ == "__main__":
    hash_to_crack = input("Enter the MD5 hash to crack: ")
    wordlist_path = input("Enter the path to the wordlist file: ")

    result = crack_md5_hash(hash_to_crack, wordlist_path)

    if result:
        print(f"\nPassword found: {result}")
    else:
        print("\nPassword not found in the wordlist.")
