#!/usr/bin/env python3

import hashlib
import time

hash_yang_dipecahkan = input("Masukkan hash MD5 yang ingin dipecahkan: ")

if len(hash_yang_dipecahkan) != 32:
    print("Kesalahan: Hash yang dimasukkan tidak valid.")

path_wordlist = input("Masukkan path ke file wordlist: ")

with open(path_wordlist, 'r', encoding='latin-1', errors='ignore') as berkas_wordlist:
    daftar_kata = berkas_wordlist.read().splitlines()

print("")
for kata_sandi in daftar_kata:
    hash_kata_sandi = hashlib.md5(kata_sandi.encode()).hexdigest()
    if hash_kata_sandi == hash_yang_dipecahkan:
        print(f"Kata sandi ditemukan: {kata_sandi}")
        break
else:
    print("Kata sandi tidak ditemukan dalam wordlist.")
